--------------------------------------------------------
--  파일이 생성됨 - 월요일-8월-24-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Package Body PKG_BOARD
--------------------------------------------------------

  CREATE OR REPLACE PACKAGE BODY "S"."PKG_BOARD" AS

  PROCEDURE PROC_BOARD_LIST(
  O_CUR   OUT   SYS_REFCURSOR
 ) AS
  BEGIN
  OPEN O_CUR FOR
  SELECT DISTINCT A.PNAME , A.CATEGORY , A.CNAME , A.PCOST
, A.DTIME, NVL(B.DDAY,'제한없음') AS DDAY ,A.PTOT
FROM
(
SELECT T2.PNAME , T2.PNAME || ' '|| T1.CNAME ||DECODE(GRID,'GR001','회권','GR002','개월권','GR003','개월권' ) AS CATEGORY
, T1.CNAME || DECODE(T1.GRID,'GR001','회','GR002','개월','GR003','개월' ) AS CNAME
, T2.PCOST 
, DECODE(PTOT, NULL, '제한없음',PTOT) AS PTOT
, NVL(T3.DTIME,'자율') AS DTIME
, NVL(T3.DDAY,'개인협의') AS DDAY
, T2.PID 
FROM COMMONS T1 , PRODUCTS T2
, DLECTURES T3
WHERE T1.CID = T2.CID
AND   T2.PID = T3.PID(+)
)A,
(
SELECT PID, PNAME, DTIME , 
    CASE 
     WHEN LENGTH(DDAY) = 1 THEN DDAY
     WHEN LENGTH(DDAY) = 2 THEN SUBSTR(DDAY, 1, 1) || '/' || SUBSTR(DDAY, 2, 1)
     WHEN LENGTH(DDAY) = 4 THEN '개인협의'
    END DDAY
FROM
(
SELECT PID, PNAME, DTIME ,NVL(DDAY,'개인협의') AS DDAY
FROM
(
SELECT PID,PNAME,DTIME,
TRIM(NVL(PT,'')||NVL(월,'')|| NVL(화,'') || NVL(수,'')||NVL(목,'')||NVL(금,'')||NVL(토,'')) AS DDAY 
FROM 
( 
SELECT T1.PID , T1.PNAME, NVL(T2.DDAY,'개인협의') AS DDAY ,NVL(T2.DTIME,'개인협의') AS DTIME
FROM PRODUCTS T1 , DLECTURES T2
WHERE T1.PID = T2.PID
)
PIVOT(
            MAX(DDAY) 
            FOR DDAY IN('PT' AS PT, '월' AS 월, '화' AS 화,'수' AS 수 ,'목' AS 목,'금' AS 금, '토' AS 토)
)
ORDER BY PID
)
)
) B
WHERE A.PID = B.PID(+)
ORDER BY PNAME,PCOST
;

  END PROC_BOARD_LIST
  ;
  
  
  
  PROCEDURE PROC_BOARD_SELECT(
  IN_SELONE  IN VARCHAR2,
  IN_SELTWO  IN VARCHAR2,
  O_CUR   OUT   SYS_REFCURSOR
 ) AS
  BEGIN
  OPEN O_CUR FOR
  SELECT DISTINCT A.PNAME , A.CATEGORY , A.CNAME , A.PCOST
, A.DTIME, NVL(B.DDAY,'제한없음') AS DDAY ,A.PTOT
FROM
(
SELECT T2.PNAME , T2.PNAME || ' '|| T1.CNAME ||DECODE(GRID,'GR001','회권','GR002','개월권','GR003','개월권' ) AS CATEGORY
, T1.CNAME || DECODE(T1.GRID,'GR001','회','GR002','개월','GR003','개월' ) AS CNAME
, T2.PCOST 
, DECODE(PTOT, NULL, '제한없음',PTOT) AS PTOT
, NVL(T3.DTIME,'자율') AS DTIME
, NVL(T3.DDAY,'개인협의') AS DDAY
, T2.PID 
FROM COMMONS T1 , PRODUCTS T2
, DLECTURES T3
WHERE T1.CID = T2.CID
AND   T2.PID = T3.PID(+)
)A,
(
SELECT PID, PNAME, DTIME , 
    CASE 
     WHEN LENGTH(DDAY) = 1 THEN DDAY
     WHEN LENGTH(DDAY) = 2 THEN SUBSTR(DDAY, 1, 1) || '/' || SUBSTR(DDAY, 2, 1)
     WHEN LENGTH(DDAY) = 4 THEN '개인협의'
    END DDAY
FROM
(
SELECT PID, PNAME, DTIME ,NVL(DDAY,'개인협의') AS DDAY
FROM
(
SELECT PID,PNAME,DTIME,
TRIM(NVL(PT,'')||NVL(월,'')|| NVL(화,'') || NVL(수,'')||NVL(목,'')||NVL(금,'')||NVL(토,'')) AS DDAY 
FROM 
( 
SELECT T1.PID , T1.PNAME, NVL(T2.DDAY,'개인협의') AS DDAY ,NVL(T2.DTIME,'개인협의') AS DTIME
FROM PRODUCTS T1 , DLECTURES T2
WHERE T1.PID = T2.PID
)
PIVOT(
            MAX(DDAY) 
            FOR DDAY IN('PT' AS PT, '월' AS 월, '화' AS 화,'수' AS 수 ,'목' AS 목,'금' AS 금, '토' AS 토)
)
ORDER BY PID
)
)
) B
WHERE A.PID = B.PID(+)
AND 
  ( (IN_SELONE IS NULL) OR 
   (CASE WHEN PTOT='제한없음' OR PTOT='1' THEN '1'
         ELSE '2' END) = IN_SELONE)
ORDER BY 
   CASE WHEN IN_SELTWO='ASC' THEN PCOST END ASC, 
   CASE WHEN IN_SELTWO='DESC' THEN PCOST END DESC 
;
  END PROC_BOARD_SELECT
  ;
  
  
PROCEDURE PROC_BOARD_MENU(
  IN_MENUNAME  IN VARCHAR2,
  O_CUR   OUT   SYS_REFCURSOR
 ) AS
  BEGIN
  OPEN O_CUR FOR
  SELECT DISTINCT A.PNAME , A.CATEGORY , A.CNAME , A.PCOST
, A.DTIME, NVL(B.DDAY,'제한없음') AS DDAY ,A.PTOT
FROM
(
SELECT T2.PNAME , T2.PNAME || ' '|| T1.CNAME ||DECODE(GRID,'GR001','회권','GR002','개월권','GR003','개월권' ) AS CATEGORY
, T1.CNAME || DECODE(T1.GRID,'GR001','회','GR002','개월','GR003','개월' ) AS CNAME
, T2.PCOST 
, DECODE(PTOT, NULL, '제한없음',PTOT) AS PTOT
, NVL(T3.DTIME,'자율') AS DTIME
, NVL(T3.DDAY,'개인협의') AS DDAY
, T2.PID 
FROM COMMONS T1 , PRODUCTS T2
, DLECTURES T3
WHERE T1.CID = T2.CID
AND   T2.PID = T3.PID(+)
)A,
(
SELECT PID, PNAME, DTIME , 
    CASE 
     WHEN LENGTH(DDAY) = 1 THEN DDAY
     WHEN LENGTH(DDAY) = 2 THEN SUBSTR(DDAY, 1, 1) || '/' || SUBSTR(DDAY, 2, 1)
     WHEN LENGTH(DDAY) = 4 THEN '개인협의'
    END DDAY
FROM
(
SELECT PID, PNAME, DTIME ,NVL(DDAY,'개인협의') AS DDAY
FROM
(
SELECT PID,PNAME,DTIME,
TRIM(NVL(PT,'')||NVL(월,'')|| NVL(화,'') || NVL(수,'')||NVL(목,'')||NVL(금,'')||NVL(토,'')) AS DDAY 
FROM 
( 
SELECT T1.PID , T1.PNAME, NVL(T2.DDAY,'개인협의') AS DDAY ,NVL(T2.DTIME,'개인협의') AS DTIME
FROM PRODUCTS T1 , DLECTURES T2
WHERE T1.PID = T2.PID
)
PIVOT(
            MAX(DDAY) 
            FOR DDAY IN('PT' AS PT, '월' AS 월, '화' AS 화,'수' AS 수 ,'목' AS 목,'금' AS 금, '토' AS 토)
)
ORDER BY PID
)
)
) B
WHERE A.PID = B.PID(+)
AND ( (IN_MENUNAME IS NULL) OR (IN_MENUNAME IS NOT NULL AND A.PNAME = IN_MENUNAME) )
;
  END PROC_BOARD_MENU
  ;  

END PKG_BOARD;

/
